/*
    Se define el paquete de los procedimientos usados en el modulo de Matricula,  al igual que las variables globales,
    parametros de cada procedimiento y retornos.
 */

CREATE OR REPLACE TYPE VARCHAR2_TABLE_TYPE AS TABLE OF VARCHAR2(200);
/

CREATE OR REPLACE PACKAGE PKG_MATRICULA AS

    -- Tabla para devolver asignaturas automáticas
    TYPE T_VARCHAR_TABLE IS TABLE OF VARCHAR2(200);

    PROCEDURE INICIAR_MATRICULA(
        P_ID_ESTUDIANTE      IN  NUMBER,
        P_ID_PERIODO         IN  NUMBER,
        P_ID_MATRICULA       OUT NUMBER,
        P_ASIGNATURAS_AUTO   OUT T_VARCHAR_TABLE,
        P_MENSAJE            OUT VARCHAR2
    );

    PROCEDURE AGREGAR_GRUPO(
        P_ID_MATRICULA   IN NUMBER,
        P_ID_GRUPO       IN NUMBER,
        P_MENSAJE        OUT VARCHAR2
    );

    PROCEDURE QUITAR_GRUPO(
        P_ID_MATRICULA   IN NUMBER,
        P_ID_GRUPO       IN NUMBER,
        P_MENSAJE        OUT VARCHAR2
    );

    PROCEDURE FINALIZAR_MATRICULA(
        P_ID_MATRICULA  IN NUMBER,
        P_MENSAJE       OUT VARCHAR2
    );

END PKG_MATRICULA;
/

/*
    Se degine el paquete con los procedimientos usados para la gestión de los grupos.
 */

CREATE OR REPLACE PACKAGE PKG_GRUPO AS

    PROCEDURE CREAR_GRUPO(
        P_NOMBRE        IN  VARCHAR2,
        P_ID_PERIODO    IN  NUMBER,
        P_ID_ASIGNATURA IN  NUMBER,
        P_ID_GRUPO      OUT NUMBER,
        P_MENSAJE       OUT VARCHAR2
    );

    PROCEDURE ASIGNAR_DOCENTE(
        P_ID_GRUPO   IN NUMBER,
        P_ID_DOCENTE IN NUMBER,
        P_MENSAJE    OUT VARCHAR2
    );

    PROCEDURE CREAR_CLASE(
    P_ID_GRUPO     IN NUMBER,
    P_DIA          IN VARCHAR2,
    P_HORA_INICIO  IN VARCHAR2,
    P_HORA_FIN     IN VARCHAR2,
    P_ID_AULA      IN NUMBER,
    P_ID_CLASE     OUT NUMBER,
    P_MENSAJE      OUT VARCHAR2
);

END PKG_GRUPO;
/

/*
    Se degine el paquete con los procedimientos usados para la gestión de las notas.
 */

CREATE OR REPLACE PACKAGE PKG_NOTA AS

    PROCEDURE CREAR_NOTA(
        P_ID_DETALLE   IN NUMBER,
        P_ID_CONFIG    IN NUMBER,
        P_VALOR        IN NUMBER,
        P_ID_NOTA      OUT NUMBER,
        P_MENSAJE      OUT VARCHAR2
    );

    PROCEDURE EDITAR_NOTA(
        P_ID_NOTA   IN NUMBER,
        P_VALOR     IN NUMBER,
        P_MENSAJE   OUT VARCHAR2
    );

    PROCEDURE LISTAR_NOTAS_ESTUDIANTE(
        P_ID_ESTUDIANTE IN NUMBER,
        P_CURSOR        OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_NOTAS_GRUPO(
        P_ID_GRUPO IN NUMBER,
        P_CURSOR   OUT SYS_REFCURSOR
    );

END PKG_NOTA;
/

CREATE OR REPLACE PACKAGE PKG_REPORTES AS

    PROCEDURE REP_MATRICULA_CARGA(
        P_ID_PERIODO IN NUMBER,
        P_CURSOR     OUT SYS_REFCURSOR
    );

    PROCEDURE REP_TOP_GRUPOS(
        P_ID_PERIODO IN NUMBER,
        P_LIMITE     IN NUMBER,
        P_CURSOR     OUT SYS_REFCURSOR
    );

    PROCEDURE REP_INTENTOS_FALLIDOS(
        P_ID_PERIODO IN NUMBER,
        P_CURSOR     OUT SYS_REFCURSOR
    );

    PROCEDURE REP_RENDIMIENTO_ASIG(
        P_ID_PERIODO IN NUMBER,
        P_CURSOR     OUT SYS_REFCURSOR
    );

    PROCEDURE REP_DISTRIB_NOTAS(
        P_ID_PERIODO IN NUMBER,
        P_CURSOR     OUT SYS_REFCURSOR
    );

    PROCEDURE REP_EVOLUCION_PROMEDIO(
        P_ID_ESTUDIANTE IN NUMBER,
        P_CURSOR        OUT SYS_REFCURSOR
    );

    PROCEDURE REP_RIESGO_PERIODO(
        P_ID_PERIODO IN NUMBER,
        P_CURSOR     OUT SYS_REFCURSOR
    );

    PROCEDURE REP_INTENTOS_ASIG(
        P_ID_PERIODO IN NUMBER,
        P_CURSOR     OUT SYS_REFCURSOR
    );

    PROCEDURE REP_TRAYECTORIA_COHORTE(
        P_ANIO_COHORTE IN NUMBER,
        P_CURSOR       OUT SYS_REFCURSOR
    );

    PROCEDURE REP_MAPA_PRERREQ(
        P_ID_ASIG_RAIZ IN NUMBER,
        P_CURSOR       OUT SYS_REFCURSOR
    );

END PKG_REPORTES;
/